### ISSUE TITLE
Any possibility of this getting an upgrade?

### ISSUE THREAD

**Issue by elementh** [TelegramBotExtensions/TelegramBotClients#4]
To the new version¿?

Thank you!

**Comment by MihaZupan** [comment]
I'm working on it.

I went back and wrote a proper implementation to back the client so that it shuld be performant no matter how many requests you throw at it.
It now also implements the `ITelegramBotClient` interface so it should be easier to consume by other components.

I'll test everything and publish it tomorrow.

**Comment by elementh** [comment]
That's amazing, thank you very much. 
I deeply appreciate your work!

**Comment by MihaZupan** [comment]
I've pushed a new version to NuGet. All that changes is that now the client name is `RateLimitedTelegramBotClient`. I suggest storing it as `ITelegramBotClient` right away since I couldn't be bothered to port all the code comments for all the functions. See [example](https://github.com/TelegramBotExtensions/TelegramBotClients#usage).

All function wrappers are now generated by a simple piece of code, so future updates should be trivial to match.

**Comment by MihaZupan** [comment]
But it might be a bit more aggressive about timings than the previous implementation.

As in sending two requests to the same chat one after the other won't count under the burst limit but will force the second one to be delayed by whatever you set in the scheduler settings (default is 1 second for private chats, 3s for groups).

This difference could be addressed later on.
